//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sixth
{
    using System;
    using System.Collections.Generic;
    
    public partial class need_product_details
    {
        public string product_id { get; set; }
        public byte[] time_stamp { get; set; }
        public byte[] photo_one { get; set; }
        public byte[] photo_two { get; set; }
        public byte[] photo_three { get; set; }
        public string lat { get; set; }
        public string @long { get; set; }
        public string title { get; set; }
        public string decription { get; set; }
        public string category { get; set; }
        public string sub_category { get; set; }
        public string super_sub_catrgory { get; set; }
        public string mobile_number { get; set; }
        public string isactive { get; set; }
        public string report_count { get; set; }
    }
}
